config/routes.rb
Rails.application.routes.draw do
  resources :word_selects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'word_selects#new'
  get 'index', to: 'word_selects#index', as: 'index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word_select.rb
class WordSelect < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/word_selects_controller.rb
class WordSelectsController < ApplicationController
  before_action :set_word_select, only: [:show, :edit, :update, :destroy]

  # GET /word_selects
  # GET /word_selects.json
  def index
    @word_select_last = WordSelect.last
  end

  # GET /word_selects/1
  # GET /word_selects/1.json
  def show
  end

  # GET /word_selects/new
  def new
    @word_select = WordSelect.new
  end

  # GET /word_selects/1/edit
  def edit
  end

  # POST /word_selects
  # POST /word_selects.json
  def create
    @word_select = WordSelect.new(word_select_params)

    respond_to do |format|
      if @word_select.save
        format.html { redirect_to "/index", notice: 'Word select was successfully created.' }
        format.json { render :show, status: :created, location: @word_select }
      else
        format.html { render :new }
        format.json { render json: @word_select.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /word_selects/1
  # PATCH/PUT /word_selects/1.json
  def update
    respond_to do |format|
      if @word_select.update(word_select_params)
        format.html { redirect_to @word_select, notice: 'Word select was successfully updated.' }
        format.json { render :show, status: :ok, location: @word_select }
      else
        format.html { render :edit }
        format.json { render json: @word_select.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /word_selects/1
  # DELETE /word_selects/1.json
  def destroy
    @word_select.destroy
    respond_to do |format|
      format.html { redirect_to word_selects_url, notice: 'Word select was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word_select
      @word_select = WordSelect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_select_params
      params.require(:word_select).permit(:noun1, :noun2, :noun3, :place1, :place2, :verb1, :verb2, :verb3, :string, :adjective1, :adjective2, :adjective3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/word_selects_helper.rb
module WordSelectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MadLibsFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/word_selects/_form.html.erb
<%= form_with(model: word_select, local: true) do |form| %>
  <% if word_select.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word_select.errors.count, "error") %> prohibited this word_select from being saved:</h2>

      <ul>
      <% word_select.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
  <div class="field">
    <%= form.label :noun1 %>
    <%= form.text_field :noun1, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :noun2 %>
    <%= form.text_field :noun2, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :noun3 %>
    <%= form.text_field :noun3, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :place1 %>
    <%= form.text_field :place1, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :place2 %>
    <%= form.text_field :place2, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :verb1 %>
    <%= form.text_field :verb1, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :verb2 %>
    <%= form.text_field :verb2, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :verb3 %>
    <%= form.text_field :verb3, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :adjective1 %>
    <%= form.text_field :adjective1, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :adjective2 %>
    <%= form.text_field :adjective2, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :adjective3 %>
    <%= form.text_field :adjective3, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Create Mad Lib", :class => 'btn' %>
  </div>
    
</div>
<% end %>

app/views/word_selects/edit.html.erb
<h1>Editing Word Select</h1>

<%= render 'form', word_select: @word_select %>

<%= link_to 'Show', @word_select %> |
<%= link_to 'Back', word_selects_path %>

app/views/word_selects/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<main role="main" class="container">
  <div class="jumbotron">

    <h1>Current Mad Lib</h1>
    <p class="lead">
      In a place called <span class="words"><%= @word_select_last.place1 %></span> there was a <span class="words"><%= @word_select_last.adjective1 %> <%= @word_select_last.noun1 %></span> who <span class="words"><%= @word_select_last.verb1 %></span>      <br> everyone there. <span class="words"><%= @word_select_last.noun2 %></span>, the <span class="words"><%= @word_select_last.adjective2 %></span> hero of our story, <span class="words"><%= @word_select_last.adjective3 %> <%= @word_select_last.verb2 %></span>      <br> the <span class="words"><%= @word_select_last.noun3 %></span> to save the day. Sadly, he had to <span class="words"><%= @word_select_last.verb3 %></span> to <span class="words"><%= @word_select_last.place2 %></span> due to tax problems.
    </p>
  </div>
  <%= link_to 'New Word Select', new_word_select_path, :class => 'btn btn-secondary' %>
</main>

<br>

app/views/word_selects/new.html.erb
<main role="main" class="container gray">
<div id="newHeader"><h1>New Mad Lib</h1></div>

<%= render 'form', word_select: @word_select %>

<%= link_to 'Back', word_selects_path, :class => 'btn btn-danger' %>
</main>

app/views/word_selects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Noun1:</strong>
  <%= @word_select.noun1 %>
</p>

<p>
  <strong>Noun2:</strong>
  <%= @word_select.noun2 %>
</p>

<p>
  <strong>Noun3:</strong>
  <%= @word_select.noun3 %>
</p>

<p>
  <strong>Place1:</strong>
  <%= @word_select.place1 %>
</p>

<p>
  <strong>Place2:</strong>
  <%= @word_select.place2 %>
</p>

<p>
  <strong>Verb1:</strong>
  <%= @word_select.verb1 %>
</p>

<p>
  <strong>Verb2:</strong>
  <%= @word_select.verb2 %>
</p>

<p>
  <strong>Verb3:</strong>
  <%= @word_select.verb3 %>
</p>

<p>
  <strong>Adjective1:</strong>
  <%= @word_select.adjective1 %>
</p>

<p>
  <strong>Adjective2:</strong>
  <%= @word_select.adjective2 %>
</p>

<p>
  <strong>Adjective3:</strong>
  <%= @word_select.adjective3 %>
</p>

<%= link_to 'Edit', edit_word_select_path(@word_select) %> |
<%= link_to 'Back', word_selects_path %>